### PR TITLE
Use phi nodes instead of alloca

### PR DESCRIPTION
**Pull request by Skepfyr**

### CODE REVIEW

**Comment by DaveTCode** [comment]
Nice, I definitely don't understand what that does but it gives me something to read up on tonight!

And the end result is that all local int64/32 get register allocations instead of sending up on the stack on normal architecture right?

**Comment by Skepfyr** [comment]
Yes, I think alloca guarantees that you're able to get a pointer to the thing which is why it stays on the stack, but I'm not entirely sure:
> The ‘alloca’ instruction is commonly used to represent automatic variables that must have an address available.  
> https://llvm.org/docs/LangRef.html#alloca-instruction

**Comment by DaveTCode** [comment]
> Yes, I think alloca guarantees that you're able to get a pointer to the thing which is why it stays on the stack, but I'm not entirely sure:
> 
> > The ‘alloca’ instruction is commonly used to represent automatic variables that must have an address available.
> > https://llvm.org/docs/LangRef.html#alloca-instruction

Did you profile it to see what difference it made on practice? Feels like it should be quite a large difference!

**Comment by Skepfyr** [comment]
So you should be incredibly dubious of these numbers but I think it takes it from 3.1 us to 1.2 us.

**Pull request merged**
